function [ Y ] = spin_spherical_harmonics(theta,phi,s,l,m)
r=0:1:(l-s);
Y = exp(1i*m*phi)*...
    sqrt(factorial(l+m)*factorial(l-m)*(2*l+1)/...
    (factorial(l+s)*factorial(l-s)*4*pi))^(1/2) *...
    (sin(theta/2))^(2*l)...
    * sum(...
    nchoosek(l-s,r) *nchoosek(l+s,r+s-m) * ...
    (-1)^(l-r-s)*(cot(theta/2))^(2*r+s-m) )*exp(1i*m*phi);
    
end

